[package]
name = "mailparse_debug"
version = "0.1.0"
authors = ["Benjamin Weber <mail@bwe.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailparse = "*"
